server:
  port: 8080
qm:
  cache:
    type: caffeine
    ttl: 300
  logger:
    log-params: false
    log-result: false
  auth:
    secret: 3
    third:
      wechat:
        app-id: 1
        redirect-uri: https://www.qmvector.com/
        app-secret: 1
  id:
    worker-id: 22
    datacenter-id: 22
  lock:
    distributed:
      type: redis
spring:
  application:
    name: example