server:
  port: 8080
qm:
  cache:
    type: caffeine
    ttl: 300
  logger:
    log-params: false
    log-result: false
  auth:
    secret: b2df428b9929d3ace7c598bbf4e496b2
    wechat:
      app-id: wx2530a86caf4887b5
      redirect-uri: https://www.qmvector.com/
  id:
    worker-id: 22
    datacenter-id: 22
spring:
  application:
    name: example